channels:
- conda-forge
dependencies:
- python=3.8.20
- pip<=24.2
- pip:
  - mlflow==2.15.1
  - numpy==1.24.4
  - pandas==2.0.3
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - scipy==1.8.1
  - xgboost==2.1.4
name: mlflow-env
